### ISSUE TITLE
Styling Relations

### ISSUE THREAD

**Issue by PatrickRobotham** [christianvoigt/argdown#168]
Is there any way to style relationships the way we style argument types?
I'd like to have thicker line widths than the default.

**Comment by christianvoigt** [comment]
At the moment you can only [customize the edge colors](https://argdown.org/guide/colorizing-maps.html#changing-edge-colors), but I will put this on my todo list.

If you want to have complete control over the look of your map, [export it as `.graphml` and edit it in yEd](https://argdown.org/guide/changing-the-graph-layout.html#layouting-in-the-yed-graph-editor). The only downside of that is, that it is a one-way-street. But you can even use the Argdown web component, if you copy & paste the svg generated by yEd into it.

**Comment by christianvoigt** [comment]
With 1.5.0 I added penwidth and arrowsize configuration options for dot ([check out the Graphviz docs for further details on these settings](https://graphviz.org/doc/info/attrs.html#d:penwidth)):

```argdown
===
dot:
 edge: {
      penwidth: 1, # thickness of edges, default 1
      arrowsize: 1 # size of arrow, default 1
    }
===

[some statement]
    <- <some argument>
```

**Comment by dleeftink** [comment]
In the online editor, using the edge penwidth/arrowsize function does not seem to update the vis.js output, freezing edits until the edge configuration is removed. 

```
===
model:
    removeTagsFromText: true
    mode: loose
   
color:
    colorScheme: iwanthue-ochre-sand
    relationColors:
        attack: "#000000"

dot:
 edge: {
      penwidth: 1, # thickness of edges, default 1
      arrowsize: 1 # size of arrow, default 1
    }
    statement:
      minWidth: 92
      margin: "0,0"
      title:
        font: arial
        fontSize: 12
        bold: true
      text:
        font: argvu
        fontSize: 20
    argument:
      title:
        font: argvu
        fontSize: 20
        bold: true
      text:
        font: argvu
        fontSize: 20
    graphVizSettings:
      rankdir: TB
      ranksep: 0
      concentrate: true
      outputorder: edgesfirst
       
vizJs:
    engine: dot

===

# Group

[1] // this is a root node
 ->[2] // emtpy space and -> indicates a child node
   ->[3]
     ->[4]
       ->[5]

[2]
 ->[4]
 ->[1]
  ><[5]
```
