### ISSUE TITLE
charactersInLine does not work

### ISSUE THREAD

**Issue by andrejdam** [christianvoigt/argdown#214]
Hi again,

I am sorry for bombarding you with issues, but I really dived into Argdown and want to learn it thoroughly.

I am trying to define the charactersInLine setting for statements. I do this:

```
===
model:
    removeTagsFromText: false

title: a title
selection:
    excludeDisconnected: false
    statementSelectionMode: not-used-in-argument

group:
    groupDepth: 5
    minWidth: 0
argument:
    minWidth: 0
statement:
    title:
        charactersInLine: 50
    text:
        charactersInLine: 150
    

===
```

But it doesn't work. The node size stays the same, which is terrible for nodes with huge content as they spread downwards and enlarge the map needlessly towards the bottom.

Am I doing something wrong?

**Comment by christianvoigt** [comment]
Hi, bug reports are really helpful, so no need to apologize for that (I am at the moment pretty occupied in "bundling hell" trying to fix webpack issues for argdown-vscode, so I do not have much time for bug fixes, but sooner or later I will get to it).

The settings you want to use are [settings](https://argdown.org/guide/changing-the-node-size.html#changing-the-node-size-for-dot-vizjs-dagre) of the DotExportPlugin (or the Dagre plugin). So you have to change your code like this:

```yaml
===
model:
    removeTagsFromText: false

title: a title
selection:
    excludeDisconnected: false
    statementSelectionMode: not-used-in-argument

dot: # this is the change
  group:
      groupDepth: 5
      minWidth: 0
  argument:
      minWidth: 0
  statement:
      title:
          charactersInLine: 50
      text:
          charactersInLine: 150
    
===
```

At the moment the "width measurement" using charactersInLine seems to be underestimating the string width (in my test the text was wider than the node).  I will rename this issue accordingly. It would be great if you could report your test results here.

If you have the same problems you might be better off using `measureLineWidth`.
